### PR TITLE
txn-layer-deposit-and-withdrawal

### PR DESCRIPTION
**Pull request by fynmanoj**

### CODE REVIEW

**Comment by avikganguly01** [comment]
@josehernandezfintecheandomx : Can you review this PR?

**Comment by avikganguly01** [comment]
Deposit service had no txn layer to validate rules (terms and settings configured at product level like limits). This creates that txn layer where txns of different type can be persisted.

**Comment by josehernandezfintecheandomx** [comment]
Well done!

Note: This PR already includes the files of the PR https://github.com/apache/fineract-cn-deposit-account-management/pull/19

**Comment by avikganguly01** [comment]
@fynmanoj : Merged as part of the other PR which was most up to date.

**Pull request closed without merging**
