### PR TITLE
[FINCN-342] sub-txn-type

### PR DESCRIPTION
**Pull request by fynmanoj**

### CODE REVIEW

**Comment by avikganguly01** [comment]
@josehernandezfintecheandomx : Can you review this PR?

**Comment by avikganguly01** [comment]
Existing Transaction types were system defined. Support for user defined (sub) txn types added to cater to use cases such as tracking purpose/ledger linked to a withdrawal txn for purpose of billpay / merchant payment / insurance premium collection, etc.

**Comment by josehernandezfintecheandomx** [comment]
Well done! Just few details in the variable names, for example create instead of update in the PUT event

**Comment by awasum** [comment]
Hello All,

DO we have a specification or JIRA ticket describing all these new changes? If we dont have these thing in open source projects, it becomes difficult for others to contribute in the future.

**Pull request merged**
