### PR TITLE
[FINCN-347] Account level access validator

### PR DESCRIPTION
**Pull request by fynmanoj**
https://mifosforge.jira.com/browse/AL-56

### CODE REVIEW

**Comment by awasum** [comment]
@fynmanoj This PR does not point to a public issue tracker or spec document. We dont understand what you are contributing and so cannot really participate. CC @apache/fineract-committers @edcable

**Comment by fynmanoj** [comment]
@awasum  Let me check whether I can  log these in Fineract JIRA

**Comment by awasum** [comment]
Please dont merge this. 
Can you rename the commit message and PR message to not include a closed Issue tracking number?
Also mention the Open source ticket number and link to this issue.

**Review by avikganguly01 — APPROVED** [review]

**Review by awasum — CHANGES_REQUESTED** [review]
Can you rename the commit message and PR message to not include a closed Issue tracking number?
Also mention the Open source ticket number and link to this issue.

**Comment by awasum** [comment]
> https://mifosforge.jira.com/browse/AL-56

Change this to a Fineract CN issue please.

**Comment by avikganguly01** [comment]
@awasum : Commit message and PR message no longer includes a closed Issue tracking number. OS ticket no and link to the improvement is updated in FINCN JIRA.

**Review by avikganguly01 — APPROVED** [review]

**Comment by avikganguly01** [comment]
@awasum : Closing the issue in FINCN JIRA now.

**Comment by awasum** [comment]
Issue: https://issues.apache.org/jira/browse/FINCN-347

**Pull request merged**
